import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#FFF8F0', // Matches the light cream background of the screen
  },
  container: {
    flexGrow: 1,
    paddingBottom: 30,
  },
  headerContainer: {
    width: '100%',
    height: 120,
    position: 'relative',
  },
  headerBg: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    opacity: 0.8,
  },
  headerOverlay: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: 'rgba(255, 248, 240, 0.6)', // Slight overlay to make text readable
  },
  headerGreeting: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
  },
  headerBrand: {
    fontSize: 18,
    color: '#000',
  },
  headerAvatarContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#FFF',
  },
  headerAvatar: {
    width: '100%',
    height: '100%',
  },
  contentSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 15,
  },
  card: {
    backgroundColor: '#FAF5ED',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    marginBottom: 20,
  },
  avatarWrapper: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    marginBottom: 30,
    borderWidth: 4,
    borderColor: '#31416D',
  },
  mainAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 65,
  },
  cameraIconContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#F1F5F9',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 4,
  },
  cameraIcon: {
    fontSize: 20,
  },
  uploadBtn: {
    backgroundColor: '#31416D',
    width: '100%',
    paddingVertical: 16,
    borderRadius: 30,
    alignItems: 'center',
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  uploadBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '500',
  },
  takePhotoBtn: {
    backgroundColor: '#E1EEF7',
    width: '100%',
    paddingVertical: 16,
    borderRadius: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#B3D4E5',
    marginBottom: 20,
  },
  takePhotoBtnText: {
    color: '#31416D',
    fontSize: 16,
    fontWeight: '500',
  },
  helpText: {
    textAlign: 'center',
    color: '#1E293B',
    fontSize: 14,
    lineHeight: 20,
  },
  saveBtn: {
    backgroundColor: '#31416D',
    width: '100%',
    paddingVertical: 18,
    borderRadius: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
  },
  saveBtnText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
  }
});
